#
# nimna - *NA folding for Nim
#
# (c) Copyright 2017 Michael Jendrusch. All rights reserved.
# This library is licensed under the MIT license.
# For more information see LICENSE.

const
  VRNA_CONVERT_OUTPUT_ALL* = 1
  VRNA_CONVERT_OUTPUT_HP* = 2
  VRNA_CONVERT_OUTPUT_STACK* = 4
  VRNA_CONVERT_OUTPUT_MM_HP* = 8
  VRNA_CONVERT_OUTPUT_MM_INT* = 16
  VRNA_CONVERT_OUTPUT_MM_INT_1N* = 32
  VRNA_CONVERT_OUTPUT_MM_INT_23* = 64
  VRNA_CONVERT_OUTPUT_MM_MULTI* = 128
  VRNA_CONVERT_OUTPUT_MM_EXT* = 256
  VRNA_CONVERT_OUTPUT_DANGLE5* = 512
  VRNA_CONVERT_OUTPUT_DANGLE3* = 1024
  VRNA_CONVERT_OUTPUT_INT_11* = 2048
  VRNA_CONVERT_OUTPUT_INT_21* = 4096
  VRNA_CONVERT_OUTPUT_INT_22* = 8192
  VRNA_CONVERT_OUTPUT_BULGE* = 16384
  VRNA_CONVERT_OUTPUT_INT* = 32768
  VRNA_CONVERT_OUTPUT_ML* = 65536
  VRNA_CONVERT_OUTPUT_MISC* = 131072
  VRNA_CONVERT_OUTPUT_SPECIAL_HP* = 262144
  VRNA_CONVERT_OUTPUT_VANILLA* = 524288
  VRNA_CONVERT_OUTPUT_NINIO* = 1048576
  VRNA_CONVERT_OUTPUT_DUMP* = 2097152


proc convertParameterFile*(iname: cstring; oname: cstring; options: cuint) {.cdecl,
    importc: "convert_parameter_file", dynlib: rnaLib.}
